/**
 * Import participant picks from the host's responses Excel into data/picks.ts.
 *
 *   npm run import-picks -- "data-source/2026 World Cup Pool Responses.xlsx"
 *
 * The parser is deliberately forgiving because the exact layout of the responses
 * file isn't known until the pool closes. It scans every sheet, finds the rows
 * that contain team names, resolves each name to a pool team (by tier), and
 * picks the most likely "name" column. It prints a full diagnostic so anything
 * it can't resolve is obvious and easy to fix.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import * as XLSX from "xlsx";
import { POOL_TEAMS, findPoolTeam } from "../data/teams";

type Cell = string;

function loadRows(file: string): { sheet: string; rows: Cell[][] }[] {
  const wb = XLSX.readFile(file);
  return wb.SheetNames.map((name) => {
    const ws = wb.Sheets[name];
    const rows = XLSX.utils.sheet_to_json<Cell[]>(ws, {
      header: 1,
      blankrows: false,
      defval: "",
      raw: false,
    });
    return { sheet: name, rows: rows.map((r) => r.map((c) => String(c ?? "").trim())) };
  });
}

function looksLikeName(s: string): boolean {
  if (!s) return false;
  if (findPoolTeam(s)) return false; // a team name is not a person's name
  return /[a-zA-Z]/.test(s) && s.length <= 60;
}

interface Entry {
  name: string;
  picks: string[]; // espnId per tier (index 0 = tier 1)
  unresolved: string[];
  conflicts: string[];
}

function parseRow(row: Cell[], nameCol: number): Entry | null {
  const teamsByTier: Record<number, string> = {};
  const unresolved: string[] = [];
  const conflicts: string[] = [];

  row.forEach((cell, i) => {
    if (i === nameCol || !cell) return;
    const team = findPoolTeam(cell);
    if (team) {
      if (teamsByTier[team.tier] && teamsByTier[team.tier] !== team.espnId) {
        conflicts.push(`tier ${team.tier}: ${cell}`);
      } else {
        teamsByTier[team.tier] = team.espnId;
      }
    } else if (/[a-zA-Z]{3,}/.test(cell) && !/^\d/.test(cell)) {
      // Looks like it might be a team but didn't resolve — flag it (skip name col).
      if (i !== nameCol) unresolved.push(cell);
    }
  });

  const resolvedTiers = Object.keys(teamsByTier).length;
  if (resolvedTiers === 0) return null;

  const picks: string[] = [];
  for (let t = 1; t <= 10; t++) picks.push(teamsByTier[t] ?? "");

  return {
    name: row[nameCol]?.trim() || "(unnamed)",
    picks,
    unresolved,
    conflicts,
  };
}

function pickBestSheet(sheets: { sheet: string; rows: Cell[][] }[]) {
  // Choose the sheet whose cells resolve to the most team names.
  let best = sheets[0];
  let bestScore = -1;
  for (const s of sheets) {
    let score = 0;
    for (const row of s.rows) for (const c of row) if (findPoolTeam(c)) score++;
    if (score > bestScore) {
      bestScore = score;
      best = s;
    }
  }
  return { ...best, score: bestScore };
}

function chooseNameColumn(rows: Cell[][]): number {
  // The name column has the most person-like, non-team text values across data rows.
  const colScores: Record<number, number> = {};
  const maxCols = Math.max(...rows.map((r) => r.length), 0);
  for (let c = 0; c < maxCols; c++) {
    let score = 0;
    for (const row of rows) if (looksLikeName(row[c] ?? "")) score++;
    colScores[c] = score;
  }
  let best = 0;
  let bestScore = -1;
  for (const [c, s] of Object.entries(colScores)) {
    if (s > bestScore) {
      bestScore = s;
      best = Number(c);
    }
  }
  return best;
}

function generateFile(entries: Entry[]): string {
  const lines = entries.map((e, i) => {
    const id = `p${String(i + 1).padStart(2, "0")}`;
    const picks = e.picks.map((p) => `"${p}"`).join(", ");
    const name = e.name.replace(/"/g, '\\"');
    return `  { id: "${id}", name: "${name}", picks: [${picks}] },`;
  });
  return `import type { Participant } from "@/lib/types";

// Generated by scripts/import-picks.ts on ${new Date().toISOString()}.
// Each pick is an ESPN team id, ordered tier 1 → tier 10. "" means no pick resolved
// for that tier — check the import log if you see blanks.

export const PICKS_ARE_PLACEHOLDER = false;

export const PARTICIPANTS: Participant[] = [
${lines.join("\n")}
];
`;
}

function main() {
  const file = process.argv[2];
  if (!file) {
    console.error('Usage: npm run import-picks -- "path/to/responses.xlsx"');
    process.exit(1);
  }
  if (!fs.existsSync(file)) {
    console.error(`File not found: ${file}`);
    process.exit(1);
  }

  const sheets = loadRows(file);
  const best = pickBestSheet(sheets);
  console.log(`\nSheets: ${sheets.map((s) => s.sheet).join(", ")}`);
  console.log(`Using sheet "${best.sheet}" (${best.score} team-name matches).`);

  const nameCol = chooseNameColumn(best.rows);
  console.log(`Name column index: ${nameCol}\n`);

  const entries: Entry[] = [];
  for (const row of best.rows) {
    const entry = parseRow(row, nameCol);
    if (entry) entries.push(entry);
  }

  // Report.
  let warnings = 0;
  entries.forEach((e) => {
    const filled = e.picks.filter(Boolean).length;
    const flags: string[] = [];
    if (filled !== 10) flags.push(`${filled}/10 picks`);
    if (e.unresolved.length) flags.push(`unresolved: ${e.unresolved.join(", ")}`);
    if (e.conflicts.length) flags.push(`conflicts: ${e.conflicts.join(", ")}`);
    if (flags.length) {
      warnings++;
      console.log(`  ⚠  ${e.name} — ${flags.join("; ")}`);
    }
  });

  console.log(`\nParsed ${entries.length} participants (${warnings} with warnings).`);
  console.log(`Pool has ${POOL_TEAMS.length} teams across 10 tiers.`);

  const out = path.join(process.cwd(), "data", "picks.ts");
  fs.writeFileSync(out, generateFile(entries));
  console.log(`\n✓ Wrote ${out}\n`);
  if (warnings) {
    console.log("Review the warnings above. Fix the responses file or edit data/picks.ts,");
    console.log("then re-run. Unmatched names usually mean a spelling alias — add it to");
    console.log("the `aliases` map in data/teams.ts.\n");
  }
}

main();
